export const FETCH_TODOS_LOADED = 'FETCH_TODOS';
export const FETCH_TODOS_LOADING = 'FETCH_TODOS_LOADING';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';

export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';

export const CHANGE_SCREEN = 'CHANGE_SCREEN';
